### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by martellaj** [tom-squires/training-questions#1]
Not an issue, but couldn't really find a better way to get in touch with you! I got tagged in a post today and subsequently found this project and tool existed... I can't believe it's 2 years old without me having any knowledge about it. 😂 Just wanted to say I'm glad you were able to fork and shape it to your community's needs, and thanks for the credit in both the README and the template itself! ✌

**Comment by tom-squires** [comment]
Haha, glad you approve! You did a great job with the original tool.
